### PR TITLE
Add more details to 2000-03-01-gem5-basics.md

### PR DESCRIPTION
**Pull request by takekoputa**
Signed-off-by: Hoa Nguyen <hoanguyen@ucdavis.edu>

### CODE REVIEW

**Comment by takekoputa** [comment]
The above commit is what would be cover in python-reminder + gem5-basic usage

**Comment by powerjg** [comment]
@takekoputa, Add me as a reviewer next time. I didn't get notified that this existed :)

**Review by powerjg — APPROVED** [review]
LGTM!

**Comment by takekoputa** [comment]
@powerjg I don't have the permission to merge so I'd leave that to you and Bobby!

**Pull request merged**
